## Ciência de Dados - Atividade 2
### Atividade prática de exploração e análise de base de dados
### Base de dados 'ENEM 2022'
---
**Docente:** Roseli Aparecida Romero  
**Discente:** Thiago Rafael Mariotti Claudio - 15611674  
**Data 15/02/2024**

# 0. Exploração inicial e limpeza

Antes mesmo de formular quaisquer hipoteses, precisamos abrir a base e realizar uma exploração inicial, fazendo uma limpeza ou busca por possíveis erros, caso necessário.  
Para isso importaremos as ferramentas necessárias, nesse caso **pandas** e **numpy** para manipulação de _datasets_ e manipulação de dados númericos, respectivamente.

In [1]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('ENEM/amostra_enem2022.csv', delimiter=',')

display(df.head(6))

print("\n\nLabel e tipagem de todas as colunas da base")
df.dtypes

,Unnamed: 0,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,IN_TREINEIRO,TP_SEXO,TP_ESCOLA,TP_COR_RACA,SG_UF_PROVA
0,2401255,441.9,477.6,424.9,436.3,740.0,0,F,2,1,MA
1,3283840,415.9,490.0,300.0,396.8,480.0,0,F,2,2,MT
2,1745004,403.0,371.8,460.2,411.0,620.0,0,F,2,1,SP
3,2781081,NaN,NaN,NaN,NaN,NaN,1,F,1,1,DF
4,1712844,466.3,545.3,548.1,486.9,720.0,0,M,2,1,PE
5,839510,NaN,NaN,NaN,NaN,NaN,0,F,1,1,SP

Label e tipagem de todas as colunas da base

Unnamed: 0           int64
NU_NOTA_CN         float64
NU_NOTA_CH         float64
NU_NOTA_LC         float64
NU_NOTA_MT         float64
NU_NOTA_REDACAO    float64
IN_TREINEIRO         int64
TP_SEXO             object
TP_ESCOLA            int64
TP_COR_RACA          int64
SG_UF_PROVA         object
dtype: object

Note que existe uma coluna sem nome (_label_). Podemos inferir que essa coluna refere-se ao UID (identificador unico) do estudante. Para isso podemos verificar se os valores nessa coluna são únicos.

In [3]:
if df['Unnamed: 0'].unique().size == df['Unnamed: 0'].size:
    print(f"A quantidade de valores unicos na coluna é IGUAL ao tamanho da coluna: {df['Unnamed: 0'].size} == {df['Unnamed: 0'].unique().size}\n")
else:
    print(f"A coluna não é composta unicamente de valores unicos.\n")

A quantidade de valores unicos na coluna é IGUAL ao tamanho da coluna: 10000 == 10000

Confirmamos que a coluna possui somente valores únicos, logo a hipotese de que essa coluna refere-se à um UID ou similar faz sentido. Para fins práticos, renomearemos essa coluna de **Unnamed: 0** para **UID_ESTUDANTE**.

In [4]:
df.rename(columns={"Unnamed: 0": "UID_ESTUDANTE"},inplace=True)

Como observado acima, as colunas já estão corretamente tipadas. Embora caibam aqui algumas observações:  
- **UID_ESTUDANTE** poderia ser do tipo _object_ (string). No entanto, ambos os tipos são intercabiaveis no contexto de identificação, e, essa coluna não tera muita relevância no estudo.
- **TP_SEXO** poderia ser do tipo _boleano_ ou _inteiro_, visto que os dados da coluna assumem apenas dois valores, **M** ou **F**. Novamente, tanto o tipo _string_ quanto os tipos mencionados acima são aplicaveis aqui.
- A mesma observação se aplica para **TP_ESCOLA**, que poderia ser _string_, **SG_UF_PROVA** que poderia ser _inteiro_ com enumeração.

In [7]:
df.dtypes

Unnamed: 0           int64
NU_NOTA_CN         float64
NU_NOTA_CH         float64
NU_NOTA_LC         float64
NU_NOTA_MT         float64
NU_NOTA_REDACAO    float64
IN_TREINEIRO         int64
TP_SEXO             object
TP_ESCOLA            int64
TP_COR_RACA          int64
SG_UF_PROVA         object
dtype: object

# 1. Visualizando e extraindo dados

Ao realizar uma visualização simples da base em formato tabular com o _display_ das primeiras 10 linhas, podemos observar que existem alguns registros númericos vazios (_NaN_). Será que podemos remover esses dados da base?

In [8]:
display(df.head(10))

,Unnamed: 0,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,IN_TREINEIRO,TP_SEXO,TP_ESCOLA,TP_COR_RACA,SG_UF_PROVA
0,2401255,441.9,477.6,424.9,436.3,740.0,0,F,2,1,MA
1,3283840,415.9,490.0,300.0,396.8,480.0,0,F,2,2,MT
2,1745004,403.0,371.8,460.2,411.0,620.0,0,F,2,1,SP
3,2781081,NaN,NaN,NaN,NaN,NaN,1,F,1,1,DF
4,1712844,466.3,545.3,548.1,486.9,720.0,0,M,2,1,PE
5,839510,NaN,NaN,NaN,NaN,NaN,0,F,1,1,SP
6,775495,NaN,440.0,533.4,NaN,660.0,0,F,1,3,BA
7,1348409,NaN,NaN,NaN,NaN,NaN,0,F,1,3,AM
8,3040163,569.4,428.9,337.1,704.6,580.0,0,M,1,1,RS
9,329325,460.7,515.8,475.2,454.1,580.0,0,M,1,3,MA

In [11]:
for col in df.columns:
    if col.type == "object":
        print(f"A coluna {col} possui {col.isnone.sum()} valores None")
    else:
        print(f"A coluna {col} possui {col.isna.sum()} valores NaN")

AttributeError: 'str' object has no attribute 'type'